### ISSUE TITLE
Is there a fast way to test for the presence of a window/control ?

### ISSUE THREAD

**Issue by RenaudBompuis** [pywinauto/py_inspect#23]
Is there a fast way to test for the presence of a window/control ?

Using `child_window()` returns fast because it just defines a spec, but any query on the returned object will take a long time to fail if the spec actually refers to something that's not on-screen.

I'd like to just know whether an element/window is available or not, quickly.
I tried to set `allow_magic_lookup=False`, but while it fails faster, it still takes a while, and you end-up having to manage a lot of try/except blocks to manage inaccessible elements.

I'm probably missing something, but anyone has any suggestions ?

**Comment by RenaudBompuis** [comment]
My bad, posted this in the wrong project, it was meant to be posted in `pywinauto` not `py_inscpect`

**Comment by CJ-Hadley** [comment]
https://www.youtube.com/watch?v=uTLsI2asox4

**Comment by vasily-v-ryabov** [comment]
This guide should contain all possible links about waiting / checking for existence: https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html
Hope it helps.
